# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.RemoveField(
            model_name='story',
            name='percent_complete',
        ),
        migrations.AddField(
            model_name='story',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='complete_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='sprint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
