# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 05:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djanban', '0004_auto_20160924_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
