# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djanban', '0005_auto_20160926_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('Doing', 'Doing'), ('Done', 'Done')], default='ToDo', max_length=5),
        ),
    ]
